# Generated by Django 2.2.2 on 2019-06-14 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Workig'), ('2', 'Break'), ('3', 'Meeting')], default='1', max_length=1)),
                ('working_hours', models.DurationField(blank=True, null=True)),
                ('breaking_hours', models.DurationField(blank=True, null=True)),
                ('meeting_hours', models.DurationField(blank=True, null=True)),
                ('work_start', models.DateTimeField(blank=True, null=True)),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('meeting_start', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
